name: mychefai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  firebase_core: ^3.12.1  # Update to the latest version
  firebase_auth: ^5.5.1   # Update to the latest version
  cloud_firestore: ^5.6.5 # Update to the latest version
  google_sign_in: ^6.1.5  # Ensure this is compatible
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.4
  http: ^1.1.0  # Added HTTP package for API calls
  # Add explicit dependency for Unicode/UTF-8 handling
  characters: ^1.3.0     # For proper character handling, including extended Unicode
  flutter_localizations:  # For localization support to handle different character sets
    sdk: flutter
  intl: ^0.19.0          # Required for localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_image_placeholder.png
    - assets/images/recipe_image_placeholder.png
    - assets/images/google_logo.png
    - assets/images/mychefai_logo.png
    - assets/images/mychefai_guy.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
          weight: 100
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
          weight: 400
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
          weight: 500
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
          weight: 700
    - family: Open Sans Italic
      fonts:
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          weight: 100
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          weight: 400
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          weight: 500
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          weight: 700